backend:
  name: test-repo

# These lines should *not* be indented
media_folder: "assets/images/projects"
public_folder: "/assets/images/projects"

# Optional: Logo and site info
site_url: https://ellee-portfolio.netlify.app
display_url: https://ellee-portfolio.netlify.app
# logo_url: https://kenalba.github.io/art-portfolio-jekyll-site/assets/images/logo.png  # Optional - add logo later

collections:
  # Professional Projects
  - name: "professional"
    label: "Professional Work"
    folder: "collections/_professional"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "hidden", default: "professional"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      
      # Simple Images (Traditional System)
      - label: "Project Images"
        name: "images" 
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "filename", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      
      # Advanced Gallery System (Optional)
      - label: "Advanced Gallery Layout"
        name: "gallery"
        widget: "list"
        required: false
        types:
          - label: "Single Image"
            name: "image"
            fields:
              - {label: "Image", name: "filename", widget: "image"}
              - {label: "Alt Text", name: "alt", widget: "string"}
              - {label: "Caption", name: "caption", widget: "string", required: false}
          
          - label: "Text Block"  
            name: "text"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Content", name: "content", widget: "markdown"}
          
          - label: "Image Carousel"
            name: "carousel"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - {label: "Image", name: "filename", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
                  - {label: "Caption", name: "caption", widget: "string", required: false}
      
      # Project Extensions (Custom Fields)
      - label: "Additional Details"
        name: "extensions"
        widget: "object"
        required: false
        fields:
          - {label: "Client", name: "client", widget: "string", required: false}
          - {label: "Project Duration", name: "project_duration", widget: "string", required: false}
          - {label: "Project Type", name: "project_type", widget: "string", required: false}
          - {label: "Status", name: "status", widget: "string", required: false}
          - {label: "Usage", name: "usage", widget: "string", required: false}
          - {label: "Applications", name: "potential_applications", widget: "string", required: false}

  # Illustration Projects  
  - name: "illustration"
    label: "Illustration Work"
    folder: "collections/_illustration"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "hidden", default: "illustration"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - label: "Project Images"
        name: "images" 
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "filename", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - label: "Additional Details"
        name: "extensions"
        widget: "object"
        required: false
        fields:
          - {label: "Series Count", name: "series_count", widget: "string", required: false}
          - {label: "Exhibition", name: "exhibition", widget: "string", required: false}
          - {label: "Print Sales", name: "print_sales", widget: "string", required: false}

  # Branding Projects
  - name: "branding"
    label: "Branding Work"
    folder: "collections/_branding"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "hidden", default: "branding"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - label: "Project Images"
        name: "images" 
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "filename", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - label: "Additional Details"
        name: "extensions"
        widget: "object"
        required: false
        fields:
          - {label: "Client", name: "client", widget: "string", required: false}
          - {label: "Brand Guidelines", name: "brand_guidelines", widget: "string", required: false}
          - {label: "Applications", name: "applications", widget: "string", required: false}

  # Academic Projects
  - name: "academic"
    label: "Academic Work"
    folder: "collections/_academic"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "hidden", default: "academic"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - label: "Project Images"
        name: "images" 
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "filename", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - label: "Additional Details"
        name: "extensions"
        widget: "object"
        required: false
        fields:
          - {label: "Institution", name: "institution", widget: "string", required: false}
          - {label: "Course", name: "course", widget: "string", required: false}
          - {label: "Research Area", name: "research_area", widget: "string", required: false}

  # Personal Projects
  - name: "personal"
    label: "Personal Work"
    folder: "collections/_personal"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "number", value_type: "int"}
      - {label: "Medium", name: "medium", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "hidden", default: "personal"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - label: "Project Images"
        name: "images" 
        widget: "list"
        required: false
        fields:
          - {label: "Image", name: "filename", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - label: "Additional Details"
        name: "extensions"
        widget: "object"
        required: false
        fields:
          - {label: "Series Count", name: "series_count", widget: "string", required: false}
          - {label: "Exhibition", name: "exhibition", widget: "string", required: false}
          - {label: "Print Sales", name: "print_sales", widget: "string", required: false}
          - {label: "Personal Note", name: "personal_note", widget: "text", required: false}

  # Site Pages (About, Contact)
  - name: "pages"
    label: "Site Pages"
    files:
      - file: "about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "About"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/about/"}
          - {label: "Content", name: "body", widget: "markdown"}
      
      - file: "contact.md"
        label: "Contact Page" 
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "Contact"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact/"}
          - {label: "Content", name: "body", widget: "markdown"}